#!/bin/sh
set -eu

test -n "${IPKG_INSTROOT:-}" && exit 0

opkg-key add /usr/share/glinet-github-jump-users/opkg-feed.pub >/dev/null 2>&1 || true
/usr/sbin/github-jump-users-setup
/usr/sbin/github-jump-users-sync >/dev/null 2>&1 || true
/etc/init.d/nginx reload >/dev/null 2>&1 || true
